### ISSUE TITLE
Add a dedicated port to control configuration and for identification

### ISSUE THREAD

**Issue by Wierzbowsky** [RBSC/Carnivore2#59]
Add a dedicated port to Carnivore2 for identification and controlling the configuration. The default port number is #F0, it must be configurable via the registers (to allow more than one Carnivore in the system, so #F1 and #F2 should be possible) and the following operations are allowed on these ports:

- Detection of the cartridge
	- Write "C" to port, then read the value. Carnivore2 will respond with its version - "2" (ASCII format)
- Identify the slot used by Carnivore2
	- Write "S" to port, then read the value. Carnivore2 will respond with its slot, for example "1" (ASCII format)
- Hide control registers
	- Write "H" to port, the control registers will be hidden
- Show control registers
	- Write "R" to port, control the registers will appear at their defined location (see below)
- Set location for control registers
	- Write "0" to port, the control registers will appear at #0F80
	- Write "1" to port, the control registers will appear at #4F80
	- Write "2" to port, the control registers will appear at #8F80
	- Write "3" to port, the control registers will appear at #CF80
- Set cartridge's device configuration
	- Write "A" to port, the cartridge will enable only the main slot (one device only)
	- Write "M" to port, the cartridge will set the default configuration (all devices enabled)

**Comment by Wierzbowsky** [comment]
Added into 2.50 BootBlock and firmware. Port can be configured in the Configuration menu

**Comment by sdsnatcher** [comment]
Same comment as #64 is valid here:

Is it really necessary to waste more of the scarce main I/O ports with this cartridge?

Why not use the Switched I/O ports?

I would recommend to take a look at the OneChipMSX switched I/O ports for some design inspiration.

This would also make the detection much simpler and standard, instead of some proprietary juggling nonsense.


I also can't see the reason to make its memory-mapped register addresses configurable. Would you care to explain what's the use case for this? Right now it gives the impression of being a classic case of over-engineering, but I might be missing something.

**Comment by Wierzbowsky** [comment]
We got this feature request from 2 different software developers, so we implemented it. The idea of user-configurable ID port rather than slot-configurable is simple - if we tie port number to slot, it will require more logical units. However, assigning certain ports to corresponding slots is not a bad idea. we will think about this. In any case, a detection routine must query all 3 ports and then slots for each port that sent the correct "pong".

**Comment by sdsnatcher** [comment]
My suggestion is to use the switched I/O ports instead of the main I/O ports.

This will even make your detection procedure much simpler and standardized, and avoid conflicts on the crowded main I/O ports range.

**Comment by sdsnatcher** [comment]
The other question that went unanswered is: what on earth will the remappable memory I/O addresses be used to?

“Two users have asked for this”, doesn’t explain what this will be used for. Maybe there’s a more elegant solution for the same problem?

**Comment by Wierzbowsky** [comment]
These addresses will be used for identification of C2s and their location in a system by various software. The remappable ports will be used to avoid conflicts when there are more than one C2 in a system. Also, if some new device using the fixed F0-F2 ports will appear, remappable ports of C2 could be used to let that device stay on its preferred port.

**Comment by sdsnatcher** [comment]
Yes, but the switched I/O ports solves all these situations without the need to waste precious main I/O ports for that.

Or to have some Frankenstein detection method…

**Comment by sdsnatcher** [comment]
Anyway, you still haven’t answered my question: what on earth will the remappable  **memory I/O addresses** be used for?

**Comment by Wierzbowsky** [comment]
I don't understand your question in technical terms. We used the 3 free remaining fixed ports to have 3 different Carnivores in a system. To make it flexible we allow to configure the port numbers used by Carnivore on-the-fly. This is the final solution and will not be changed. We may, however, assign ports based on the slot location of Carnivore with the power-on event in the future versions of the firmware (to avoid conflicts), but this is not 100% sure.

You are welcome to make your own fork and use whatever ports you feel necessary.

**Comment by sdsnatcher** [comment]
> I don't understand your question in technical terms. 

Ok. A long explanation would require more free time than I have right now. Please give me some days until I try to dig some time for that.

> You are welcome to make your own fork and use whatever ports you feel necessary.

Forks would only lead to fragmentation of an already scarce base of developers. It's better to try to find some consensus first.

**Comment by sdsnatcher** [comment]
Meanwhile, could you please explain what's the [use-case](https://en.wikipedia.org/wiki/Use_case) for this specific feature? This is the feature that sounds like nonsense to me, causing the rest of the I/O design to become a [Rube Goldberg machine](https://en.wikipedia.org/wiki/Rube_Goldberg_machine) just to support it:

> Set location for control registers
> 
> - Write "0" to port, the control registers will appear at #0F80
> - Write "1" to port, the control registers will appear at #4F80
> - Write "2" to port, the control registers will appear at #8F80
> - Write "3" to port, the control registers will appear at #CF80

**Comment by Wierzbowsky** [comment]
The location of the configuration registers may be altered by certain programs to prevent polluting of the data in #4F80. The Boot Menu and Carnivore2's utilities have a gap in the code at #4F80 to keep the registers. But in some cases it may be more convenient to move them elsewhere instead of minding the gap.

**Comment by sdsnatcher** [comment]
Tip: It's always good to read the [MSX Hardware Design guidelines](https://www.msx.org/wiki/Hardware_Design) before designing a project, or making modifications.

If your problem is the "polluting of the data in #4F80", simply moving your registers to the safe 6000h~7FFFh range should be enough to solve this case.

There's no need to have reconfigurable register memory addresses.

**Comment by Wierzbowsky** [comment]
It's always good to read MSX Wiki before suggesting the "safe" area that is used by ASCII mapper for page switching. ;)
https://www.msx.org/wiki/MegaROM_Mappers#ASC8_.28ASCII.29

**Comment by sdsnatcher** [comment]
Yes, I know this area is used for ASCII mapper page switching. And such software specifically use the addresses 6000h, 6800h, 7000h and 7800h.  AFAIK such megaROM software just don't go writing anywhere like crazy. But if you know any exceptions, please let me know.

You could, i.e., put your register at 7FF0h, just like a floppy drive interface, and nobody would write at this address out of blue, unless they really want to crash even most of the floppy disk interfaces.

Or maybe I'm missing what exactly what this register of yours does.


And if you really, really, really, really want to be on the safe side, you can implement a simple logic to enable the 7FF0h register that is very similar to the one present on the flashROM chips to enable writes. For example In order to the 7FF0h register to be enabled, you have to write "CRN2" to the address 7FF1h. Any different writes (other addresses on that frame, or different values to 7FF1h) before the CRN2 is completed would cancel the process.
